name: LOC Badge

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Count lines
        run: cloc . --csv --out=loc.csv

      - name: Generate badge
        run: |
          CODE=$(tail -n 1 loc.csv | cut -d ',' -f5)
          # Download SVG badge from shields.io
          curl -o loc-badge.svg "https://img.shields.io/badge/lines-$CODE-blue"

      - name: Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B badges
          git add loc.csv loc-badge.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update LOC badge [skip ci]"
            git push --force origin badges
          fi
